# Generated by Django 5.1.4 on 2025-03-16 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='task',
        ),
    ]
