# Generated by Django 5.1.4 on 2025-03-16 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_remove_goal_task'),
        ('tasks', '0002_category_alter_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goals.goal'),
        ),
    ]
